version: "3.7"
services:
  vetsoft-api:
    image: mcr.microsoft.com/playwright:v1.51.1-jammy
    command: >
      bash -c "
      echo 'Iniciando configuração do serviço...' &&
      apt-get update && 
      apt-get install -y git && 
      echo 'Verificando diretório /app...' &&
      if [ -d '/app/.git' ]; then
        echo 'Repositório já existe, atualizando...' &&
        cd /app &&
        git reset --hard &&
        git pull;
      else
        echo 'Limpando diretório /app...' &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        echo 'Clonando repositório...' &&
        git clone https://github.com/jeanjonathas/webscraping.git /app;
      fi &&
      cd /app/vetsoft && 
      echo 'Instalando dependências Node.js...' &&
      npm config set registry https://registry.npmjs.org/ &&
      npm install --no-fund --no-audit --legacy-peer-deps --force && 
      echo 'Instalando TypeScript globalmente...' &&
      npm install -g typescript &&
      echo 'Instalando browsers do Playwright...' &&
      npx playwright install chromium &&
      echo 'Compilando TypeScript...' &&
      npm run build &&
      echo 'Verificando middleware de autenticação...' &&
      ls -la dist/middlewares/ || true &&
      echo 'Iniciando servidor...' &&
      NODE_ENV=production npm run start"
    environment:
      - VETSOFT_USERNAME=supervet
      - VETSOFT_PASSWORD=Je@nfree16
      - SERVER_PORT=3000
      - SUPABASE_URL=https://wmtozvpyyuuletkgkwpp.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdG96dnB5eXV1bGV0a2drd3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTQ0MTIsImV4cCI6MjA2MTYzMDQxMn0.__E208S6aQUdguojnWpdB53zt_qo0x-aE84ALgLMSro
      - NODE_ENV=production
      - DISPLAY=:99
      - API_KEY=Je@nfree2525
      - DOCKER_ENV=true
      - HEADLESS=true
    volumes:
      - vetsoft_data:/app
    networks:
      - vetsoft_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.vetsoft-api.rule=Host(`apivetsoft.supervet.app`)
        - traefik.http.routers.vetsoft-api.entrypoints=websecure
        - traefik.http.routers.vetsoft-api.tls=true
        - traefik.http.routers.vetsoft-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.vetsoft-api.loadbalancer.server.port=3000
        - traefik.http.services.vetsoft-api.loadbalancer.passHostHeader=true
        - traefik.http.routers.vetsoft-api.service=vetsoft-api
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  vetsoft_data:
    name: vetsoft_data

networks:
  vetsoft_network:
    external: true
    name: ralliugaNet